[project]
name = "veda-open-source-network"
version = "0.1.0"
description = "An experimental visualization of VEDA team member's contributions to open source repositories"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pydantic>=2.11.9", "pygithub>=2.8.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]
