name: Build data

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ secrets.DS_RELEASE_BOT_ID }}
          private-key: ${{ secrets.DS_RELEASE_BOT_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - uses: astral-sh/setup-uv@v6
      - name: Build
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b build-data
          uv run contributor-network fetch
          uv run contributor-network build
          git add .
          git commit -m "chore: update data"
          git push -u origin build-data
      - name: Create PR
        run: gh pr create --fill
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
