name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
      - name: Format
        run: ruff format --check --diff
      - name: Type check (Python)
        run: uv run mypy
      - name: Test (Python)
        run: uv run pytest
      - name: Type check (TypeScript)
        run: npm run typecheck
      - name: Test (TypeScript)
        run: npm test
      - name: Generate data
        run: uv run contributor-network build
      - name: Build frontend
        run: npm run build
