name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci
      - uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3
      - name: Format
        run: ruff format --check --diff
      - name: Type check (Python)
        run: uv run mypy
      - name: Test (Python)
        run: uv run pytest
      - name: Type check (TypeScript)
        run: npm run typecheck
      - name: Test (TypeScript)
        run: npm test
      - name: Build
        run: uv run contributor-network build
