name: Deploy to Github Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: astral-sh/setup-uv@v6
      - name: Build
        run: uv run contributor-network build data dist
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"
      - id: deployment
        uses: actions/deploy-pages@v4
